# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  #    allowed_methods_listener:  true
  routing_loader:
    include_format : false

  format_listener:
    rules:
      - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
  view:
    view_response_listener: true
    formats:
      json: true

