#index:
#    path: /
#    controller: App\Controller\DefaultController::index
App:
  type: rest
  resource : App\Controller\MedecinController
  prefix : api

api_login_check:
  path: /api/login_check
  methods:  [POST]

App1:
  type: rest
  resource : App\Controller\PatientAPIController
  prefix : api
