#index:
#    path: /
#    controller: App\Controller\DefaultController::index
App:
  type: rest
  resource : App\Controller\MedecinAPIController
  prefix : api

App1:
  type: rest
  resource : App\Controller\PatientAPIController
  prefix : api
