#index:
#    path: /
#    controller: App\Controller\DefaultController::index
App:
  type: rest
  resource : App\Controller\MedecinController
  prefix : api

api_logout:
  path: /api/logout

App1:
  type: rest
  resource : App\Controller\PatientAPIController
  prefix : api
